webproject/inventory/urls.py
from django.conf.urls import url
from django.urls import path
from .views import *
from . import views

app_name = 'inventory'
urlpatterns = [
    path('', views.index, name = 'index'),
    path('<int:item_id>/', views.detail, name = 'detail'),
    path('add_model/', views.add_model, name = 'add_model'),



]

webproject/webproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('inventory.urls')),
]

webproject/inventory/models.py
from django.db import models

# Create your models here.

class Item(models.Model):
    item_name = models.CharField(max_length=200)
    item_count = models.IntegerField(default = 0)
    total_unit = models.IntegerField(default = 0)

    def __str__(self):
        return self.item_name


class ItemModel(models.Model):
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    model_name = models.CharField(max_length = 200)
    item_count = models.IntegerField(default = 0)
    item_price = models.IntegerField(default = 0)

    def __str__(self):
        return self.model_name

webproject/inventory/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.http import Http404
from .models import *

# Create your views here.


def index (request):
    item_list = Item.objects.all()

    for item in item_list:
        item.item_count = item.itemmodel_set.count()
        a = item.itemmodel_set.all()

        n = 0

        for i in a:
            n = n + i.item_count
        item.total_unit = n


    context = {'item_list' : item_list,
    }
    return render(request, 'index.html', context)


def add_model(request):
    mname = request.POST["mname"]
    itemno = request.POST["itemno"]
    itemprice = request.POST["itemprice"]
    itemtype = request.POST["itemtype"]
    newitem = Item.objects.get(pk=itemtype)

    newmodel = newitem.itemmodel_set.create(model_name = mname, item_count = itemno, item_price = itemprice)
    return render(request, 'index.html')


def detail(request, item_id):
    try:
        item = Item.objects.get(pk = item_id)
        item.item_count = item.itemmodel_set.count()
    except Item.DoesNotExist :
        raise Http404("The Item Does not Exist")
    return render(request, 'detail.html', {'item' : item})

webproject/inventory/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <title>{% block title%} {% endblock %}</title>
  </head>

  {% load static %}
  <link rel="stylesheet" type="text/css" href="{% static '/css/style.css' %}"/>
  <link rel="stylesheet" type="text/css" href="{% static '/css/bootstrap.min.css' %}"/>

  <body>

    <nav class="navbar navbar-expand navbar-dark bg-dark">
  <a class="navbar-brand" href="{% url 'inventory:index' %}">Inventory Manager</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample02" aria-controls="navbarsExample02" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarsExample02">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'inventory:index' %}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-md-0">
      <input class="form-control" type="text" placeholder="Search">
    </form>
  </div>
</nav>

    <br>
    <div class="container">

      {% block body %}


      {% endblock%}

    </div>

  </body>
</html>

webproject/inventory/templates/detail.html
{% extends 'base.html' %}

{% block title %} {{item.item_name}}{% endblock %}

{% block body %}
<h1>{{item.item_name}} - {{item.item_count}} Items</h1>
<br>
<br>


{% for itemmodel in item.itemmodel_set.all %}
<p>{{itemmodel.model_name}}   -    {{itemmodel.item_count}}     -    {{itemmodel.item_price}}</p>

{% endfor %}



{% endblock %}

webproject/inventory/templates/index.html
{% extends 'base.html' %}

{% block title%} Your Inventory {% endblock %}
{% block body %}

{% if item_list %}


<table style="width:100%">
  <tr>
    <th>Item Name</th>
    <th>No. of Models</th>
    <th>Total Available</th>
  </tr>
  {% for item in item_list %}
  <tr>
    <td>  <a href="{% url 'inventory:detail' item.id %}">{{item.item_name}}</a></td>
    <td>{{item.item_count}}</td>
    <td>{{item.total_unit}}</td>
  </tr>
  {% endfor %}

</table>


{% else %}
      <p>No items are available</p>

{% endif %}

<br>
<br>
<br>
<footer>

  <h2>Add new Item</h2>

  <div class="container">
      <form action="{% url 'inventory:add_model' %}" method="POST">
          <br>
          {% csrf_token %}
          <label for="mname">Model Name</label>
          <input type="text" id="mname" name="mname" value="">
          <label for="itemno">No of Items</label>
          <input type="text" id="itemno" name="itemno" value="">
          <label for="itemprice">Price of Each Item</label>
          <input type="text" id="itemprice" name="itemprice" value="">
          <label for="itemtype">Item Type</label>
          <select name="itemtype">
            {% for item in item_list%}
            <option value="{{forloop.counter }}">{{item.item_name}}</option>
            {% endfor %}

          </select>
      <button type="submit" class="btn btn-primary" name="button">Add Item</button>

      </form>

  </div>

</footer>




{% endblock %}